[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
original_class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
abi = "abis/deployments/dojo_world_world.json"
address = "0x446f1f19ba951b59935df72974f8ba6060e5fbb411ca21d3e3e3812e3eb8df8"
transaction_hash = "0x49f6a733ae427972b1f180d60fb6767bfb47859393ca500de6b73c8f37bef10"
block_number = 3
seed = "dojo_starter"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
original_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x7ec42d76c6d876b8f219c20b6a152fe35fe2afc62c471b29ba689c2f6a075b3"
class_hash = "0x47a4133010941302858d4b1a0be8bf72bf0e737924beea9e348f2861b3b833c"
original_class_hash = "0x47a4133010941302858d4b1a0be8bf72bf0e737924beea9e348f2861b3b833c"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x1c2ca4ec06ab7989adbe461a49f21c3b5dde7bb46671778bbcd90d4994dbfd9"
original_class_hash = "0x1c2ca4ec06ab7989adbe461a49f21c3b5dde7bb46671778bbcd90d4994dbfd9"
abi = "abis/deployments/models/dojo_starter_models_health_health.json"
name = "dojo_starter::models::health::health"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "value"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4e8f1493d9001823c7b93aabed617a1f3bbe8ee17b42ab85e823a0ef4ef136"
original_class_hash = "0x4e8f1493d9001823c7b93aabed617a1f3bbe8ee17b42ab85e823a0ef4ef136"
abi = "abis/deployments/models/dojo_starter_models_inventory_inventory.json"
name = "dojo_starter::models::inventory::inventory"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "item0_count"
type = "u8"
key = false

[[models.members]]
name = "item1_count"
type = "u8"
key = false

[[models.members]]
name = "item2_count"
type = "u8"
key = false

[[models.members]]
name = "item3_count"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x23c28dcfad6be01ca6509fdb35fd2bed6622238397613c60da5d387a43c38d0"
original_class_hash = "0x23c28dcfad6be01ca6509fdb35fd2bed6622238397613c60da5d387a43c38d0"
abi = "abis/deployments/models/dojo_starter_models_moves_moves.json"
name = "dojo_starter::models::moves::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2e9c42b868b520d54bff1b7f4c9b91f39bb2e2ad1c39d6484fb5d8a95382e01"
original_class_hash = "0x2e9c42b868b520d54bff1b7f4c9b91f39bb2e2ad1c39d6484fb5d8a95382e01"
abi = "abis/deployments/models/dojo_starter_models_position_position.json"
name = "dojo_starter::models::position::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x454e5ecbff55282e4d24c66a4a51f03d3a7defdb21dbd35e72f7be36b5e1559"
original_class_hash = "0x454e5ecbff55282e4d24c66a4a51f03d3a7defdb21dbd35e72f7be36b5e1559"
abi = "abis/deployments/models/dojo_starter_models_random_random.json"
name = "dojo_starter::models::random::random"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "value"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x120bf5a42d1207b463c9cca56f86b46295cd75cd707bc02260bcb14c5478714"
original_class_hash = "0x120bf5a42d1207b463c9cca56f86b46295cd75cd707bc02260bcb14c5478714"
abi = "abis/deployments/models/dojo_starter_models_state_state.json"
name = "dojo_starter::models::state::state"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "health"
type = "u8"
key = false

[[models.members]]
name = "points"
type = "u8"
key = false

[[models.members]]
name = "money"
type = "u8"
key = false
