kind = "DojoContract"
class_hash = "0x7289b11b4afb5a1250389e860205829fbc0888bf28109e30c1a8fa92e637979"
original_class_hash = "0x7289b11b4afb5a1250389e860205829fbc0888bf28109e30c1a8fa92e637979"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::actions::actions"
