kind = "DojoContract"
class_hash = "0x47a4133010941302858d4b1a0be8bf72bf0e737924beea9e348f2861b3b833c"
original_class_hash = "0x47a4133010941302858d4b1a0be8bf72bf0e737924beea9e348f2861b3b833c"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::actions::actions"
