kind = "DojoContract"
class_hash = "0x15a1c8cdb1414cd57c7816bc0559e5eb438661c288222fc41cf6d97604b323"
original_class_hash = "0x15a1c8cdb1414cd57c7816bc0559e5eb438661c288222fc41cf6d97604b323"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::actions::actions"
