kind = "DojoContract"
class_hash = "0x1b322900dc07d4df738480c4b4b23a6f73e0b690eff737a9b71e06688ffc21f"
original_class_hash = "0x1b322900dc07d4df738480c4b4b23a6f73e0b690eff737a9b71e06688ffc21f"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_starter_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::actions::actions"
