kind = "DojoModel"
class_hash = "0x31ef945f94c13e6069ada68684ac5a210906c3d3351d7a2d7a84d441827a7e7"
original_class_hash = "0x31ef945f94c13e6069ada68684ac5a210906c3d3351d7a2d7a84d441827a7e7"
abi = "manifests/dev/abis/base/models/dojo_starter_models_state_state.json"
name = "dojo_starter::models::state::state"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "health"
type = "u8"
key = false

[[members]]
name = "points"
type = "u8"
key = false

[[members]]
name = "money"
type = "u8"
key = false

[[members]]
name = "shop_slot"
type = "u8"
key = false
