kind = "DojoModel"
class_hash = "0x4e8f1493d9001823c7b93aabed617a1f3bbe8ee17b42ab85e823a0ef4ef136"
original_class_hash = "0x4e8f1493d9001823c7b93aabed617a1f3bbe8ee17b42ab85e823a0ef4ef136"
abi = "manifests/dev/abis/base/models/dojo_starter_models_inventory_inventory.json"
name = "dojo_starter::models::inventory::inventory"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "item0_count"
type = "u8"
key = false

[[members]]
name = "item1_count"
type = "u8"
key = false

[[members]]
name = "item2_count"
type = "u8"
key = false

[[members]]
name = "item3_count"
type = "u8"
key = false
